version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: echo 'export USER=root' >> $BASH_ENV
      - run:
          name: Install Fish
          command: .circleci/install-fish.sh
      - run:
          name: Test
          command: .circleci/test.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
